### ISSUE TITLE
Are you aware of Jiangly's Debug Template?

### ISSUE THREAD

**Issue by piyush26c** [hh2048/xcpc#2]
@hh2048 First, thank you for summarizing all of Jiangly's CP templates in one repository.

My Request:
Please share the debug template used by Jiangly, if it exist. Or comment on how the coder Jiangly debug the code?

**Comment by hh2048** [comment]
Unfortunately, from my observation, jiangly doesn't have a dedicated code debugging template (you can see his competition screen recordings on [jiangly's personal video platform](https://space.bilibili.com/130648068?spm_id_from=333.337.0.0) ), and generally uses `cerr` to simulate intermittent code runs. If you need a debugging template, you can search for tourist's approach (his code introduces a local file `“algo/debug.h”`), and there are quite a few contestants who have shared their code in [this blog](https://codeforces.com/blog/entry/91347?#comment-798869) on codeforces; of course, I have [a version](https://github.com/hh2048/XCPC/blob/main/01%20-%20%E5%B8%B8%E7%94%A8%E5%9C%A8%E7%BA%BF%E6%A8%A1%E6%9D%BF%E6%B1%87%E6%80%BB/01%20-%20%E5%88%9D%E5%A7%8B%E4%B8%8E%E6%9D%82%E7%B1%BB/00%20-%20wida.h) of my own in my codebase for reference.
Thanks for your interest in my codebase, and hope this helps.~

**Comment by piyush26c** [comment]
Thank you for the comment @hh2048.
