### ISSUE TITLE
请问这个模板的目录和页首是怎么制作的

### ISSUE THREAD

**Issue by 2018liuzhiyuan** [hh2048/xcpc#6]

**Comment by hh2048** [comment]
目录是因为我使用 `Typora` 这款 Markdown 编辑器中编辑导出，其会自动生成一个内嵌的 PDF 目录；而使用  `PdgCntEditor` 这款 PDF 插件可以获取这一内嵌目录并转换为 TXT 。随后在 Word 中编辑样式即可。

页首，如果您指的是封面的话，我是使用 `Photoshop` 进行排版的。

希望对你有所帮助。

**Comment by 2018liuzhiyuan** [comment]
感谢!
页首我指的是每一章都能显示自己这章节的名称，这很实用，请问是怎么处理的

**Comment by hh2048** [comment]
是在制作完全部工序后使用 PDF 编辑器批量编辑的页首。使用的软件是 `福昕高级PDF编辑器` :P
